language: python

python:
  - "3.4"

cache:
  apt:
  directories:
    - .tox
    - .cache

services:
 - redis-server

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libjpeg62 libjpeg62-dev zlib1g-dev

install:
 - pip install -U pip wheel
 - pip install -q tox hide-env codecov

script:
 - set -o pipefail
 - tox -e flake8 | hide-env GH_TOKEN PYPI_PASSWORD
 - tox -e isort | hide-env GH_TOKEN PYPI_PASSWORD
 - tox -e pillow | hide-env GH_TOKEN PYPI_PASSWORD
 - tox -e django111 | hide-env GH_TOKEN PYPI_PASSWORD
 - tox -e django18 | hide-env GH_TOKEN PYPI_PASSWORD
 - tox -e redis | hide-env GH_TOKEN PYPI_PASSWORD
 - tox -e coverage-report | hide-env GH_TOKEN PYPI_PASSWORD
 - tox -e docs | hide-env GH_TOKEN PYPI_PASSWORD

after_success:
 - codecov
 - git config --global user.name "semantic-release"
 - git config --global user.email "semantic-release@travis"
 - pip install python-semantic-release
 - semantic-release publish | hide-env GH_TOKEN PYPI_PASSWORD



